# agent_cli.py
# Very small "agent" runner. It reads task.txt, tries to handle the "fibonacci" grading task,
# writes a small Python file, runs it, and writes output.txt (uploaded by the workflow).

import re, os, subprocess, sys

def read_file(path):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read().strip()
    except Exception:
        return ''

task = read_file('task.txt')
client_id = read_file('client_id.txt')

output_lines = []
output_lines.append(f"CLIENT_ID:{client_id}")

# Simple handler: look for an "<N>th fibonacci" phrase and run Python to compute it.
m = re.search(r'(\d+)(?:st|nd|rd|th)?\\s+fibonacci', task.lower())
if m:
    n = int(m.group(1))
    # write a safe python program to compute the nth Fibonacci number with F0=0,F1=1
    code = f\"\"\"# autogenerated by agent_cli.py
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

if __name__ == '__main__':
    print(fib({n}))
\"\"\"
    fname = 'task_program.py'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(code)
    try:
        proc = subprocess.run([sys.executable, fname], capture_output=True, text=True, timeout=20)
        if proc.returncode == 0:
            output_lines.append(proc.stdout.strip())
        else:
            output_lines.append('ERROR running generated program:')
            output_lines.append(proc.stderr.strip())
    except Exception as e:
        output_lines.append('EXCEPTION: ' + str(e))
else:
    # Fallback: echo the task back (agent didn't match a special handler)
    output_lines.append("AGENT NOTE: no special handler for this task.")
    output_lines.append("RECEIVED TASK: " + task)

# Write output.txt (artifact)
with open('output.txt', 'w', encoding='utf-8') as f:
    f.write("\\n".join(output_lines))

# Also print to stdout for Actions logs
print("\\n".join(output_lines))
